### ISSUE TITLE
Unauthorised API Access, Account Not PCI Certified 

### ISSUE THREAD

**Issue by harshad26** [eWAYPayment/eway-rapid-ruby#8]
get error when try to payment with live credentials

**Comment by incarnate** [comment]
Hi @harshad26 

This usually occurs when you use the Direct method to send un-encrypted card information. If your system is PCI certified you can contact eWAY to allow this method for your account. Otherwise you can make use of [Client Side Encryption](https://eway.io/api-v3/#client-side-encryption) to protect the card data, or use an alternate Rapid method.
